apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: {{default loadbalancer .Values.service.type}}
  selector:
    name: {{.Values.labels.deployment.name}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      nodePort: {{.Values.service.nodePort}}
